version: '3.8'

services:
  gmlogger:
    build: .
    volumes:
      - .:/app
      - ./chroma_db:/app/chroma_db
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
